#import <Flutter/Flutter.h>

@interface AppLifeManage : NSObject<FlutterPlugin>

//#define ON_CREATE  @"ON_CREATE"
//#define ON_START  @"ON_START"
//#define ON_RESTART  @"ON_RESTART"
//#define ON_RESUME  @"ON_RESUME"
//#define ON_STOP  @"ON_STOP"
//#define ON_PAUSE  @"ON_PAUSE"
//#define ON_DESTROY  @"ON_DESTROY"

//ON_CREATE
#define DID_FINISH_LAUNCHING_WITH_OPTIONS @"DID_FINISH_LAUNCHING_WITH_OPTIONS"
//ON_PAUSE
#define APPLICATION_WILL_RESIGN_ACTIVE @"APPLICATION_WILL_RESIGN_ACTIVE"
//ON_STOP
#define APPLICATION_DID_ENTER_BACKGROUND @"APPLICATION_DID_ENTER_BACKGROUND"
//ON_START
#define APPLICATION_WILL_ENTER_FOREGROUND @"APPLICATION_WILL_ENTER_FOREGROUND"
//ON_RESUME
#define APPLICATION_DID_BECOME_ACTIVE @"APPLICATION_DID_BECOME_ACTIVE"
//ON_DESTROY
#define APPLICATION_WILL_TERMINATE @"APPLICATION_WILL_TERMINATE"

+ (void)registerLife :(NSString *)type;

@end
